### PR TITLE
feat: Added Kustomize configs

### PR DESCRIPTION
**Pull request by imzainhafeez**
Contains Kustomize configuration files for our Docker Project. Customized container names for our staging and dev environments through the use of Kustomization.

### CODE REVIEW

**Review by Abdullahxz — CHANGES_REQUESTED** [review]
Please make changes as requested in three other PRs. Will review this once those changes have been made here too.

**Review by Abdullahxz — CHANGES_REQUESTED** [review]
Kindly have different namespaces for dev and staging environment. Additionally, add environment labels to objects belonging to a certain environment.

**Comment by imzainhafeez** [comment]
> Kindly have different namespaces for dev and staging environment. Additionally, add environment labels to objects belonging to a certain environment.

Fixed.

**Review by Abdullahxz — APPROVED** [review]
LGTM, approved.

**Review by Abdullahxz — CHANGES_REQUESTED** [review]
Please also add resource requests and limits for each env. Also explain how you determined the appropriate resources for each pod. Dev env will have slight less resources than staging.

**Comment by imzainhafeez** [comment]
> Please also add resource requests and limits for each env. Also explain how you determined the appropriate resources for each pod. Dev env will have slight less resources than staging.

Added resource requests and limits for each env. I created minikube with 45GB approx of storage, 3GB approx of memory and 2 cpu. I allocated limit of 0.4 cpu and 256MB of memory for mongo-express in prod env. I did this considering we need resources for other services as well. This is rough estimated values. We can properly determine these by doing load testing and then manually monitor the cpu and memory usages and then determine the requests and limits for the resources. Or if we have some tool attached for monitoring like prometheus, we can execute queries to determine the resource requirements by putting loads at different levels. For better view, we can integrate grafana with it to have a more user-friendly view.

**Review by Abdullahxz — APPROVED** [review]
Please give this a read https://sysdig.com/blog/kubernetes-limits-requests/

**Pull request merged**
